package com.peoplefirst.agent.intent;

public enum AgentIntent {
    CHECK_BALANCE,
    CHECK_TEAM_BALANCES,
    APPLY_LEAVE,
    CANCEL_LEAVE,
    EDIT_LEAVE,
    VIEW_LEAVES,
    VIEW_PENDING_APPROVALS,
    APPROVE_LEAVE,
    REJECT_LEAVE,
    SEND_BACK_LEAVE,
    CHECK_POLICY,
    WELLBEING_INQUIRY,
    STRESS_EXPRESSION,
    TICKET_INQUIRY,
    RAISE_TICKET,
    ADMIN_DIRECT_EDIT,
    VIEW_ON_LEAVE,
    GREETING,
    UNKNOWN
}
